//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryorCalendarLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Users = new HashSet<User>();
        }
    
        public System.Guid Group_ID { get; set; }
        public System.Guid Leader_ID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
